routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::user()){
    	return redirect()->route('events.index');
	}
	else{
		return redirect()->route('login');
	}
});
/*Route::get('/', function(\Illuminate\http\Request $request){
	$user = $request->user();
	//dd($user->hasRole('Admin'));
	//Change to when having can
	dd($user->can('Add Candidate'));
});*/

// Authenticated Web Pages
//Route::group(['middleware' => 'auth'], function(){
Route::resource('candidates', 'CandidateController');
Route::resource('students', 'StudentController');
Route::resource('positions', 'PositionController');
Route::resource('results', 'ResultController');
Route::resource('votes', 'VoteController');
Route::resource('events', 'EventController');
Route::resource('users', 'UserController');
Route::post('votes/{votes}/validate', 'VoteController@ValidateStudent')->name('votes.ValidateStudent');
Route::post('votes/{votes}/start', 'VoteController@StartVoting')->name('votes.StartVoting');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Candidate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Candidate extends Model
{


    public $timestamps = false;
    
    protected $fillable = ['lastname', 'firstname', 'position_id', 'event_id', 'image'];

    public function position(){
        return $this->belongsTo('App\Position');
    }
}

app/Http/Controllers/CandidateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\Candidate;
use App\Event;
use Session;
use File;

class CandidateController extends Controller
{
    public function index()
    {
        $candidates = Candidate::paginate(10);
        return view('candidates.index')->withCandidate($candidates);
    }

    public function create()
    {

    }

    public function store(Request $request)
    {
        /*$this->validate($request, [
            'lastname'=>'required',
            'firstname'=>'required',
            'position_id'=>'required',
            ]);*/

        $filename = "";
        if($request -> hasFile('image')){
            $filename = str_replace(' ', '', $request->lastname . $request->firstname.'.jpeg');
            $file = $request->image;
            $file->move('images', $filename);
        }
        $candidates = New Candidate;

        $candidates->img_url = "/images/" . $filename;
        $candidates->firstname = $request->firstname;
        $candidates->lastname = $request->lastname;
        $candidates->position_id = $request->position_id;
        $candidates->event_id = $request->event_id;


        $candidates->save();

        return redirect()->route('events.show', $request -> event_id)->with('message', 'Candidate added successfully');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        //
        $candidates = Candidate::find($id);
        return view('candidates.edit')->withCandidates($candidates);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'lastname'=>'required',
            'firstname'=>'required',
        ]);

        $filename = "";
        $image_path = "/images/" . $request -> lastname . $request -> firstname . '.jpeg';
        if($request -> hasFile('image')){
            $filename = str_replace(' ', '', $request -> lastname . $request -> firstname.'.jpeg');
            $file = $request -> image;
            $file->move('images', $filename);
        }

        $candidates = Candidate::find($request->id);
        $image = $candidates->img_url;

        $candidates->firstname = $request->firstname;
        $candidates->lastname = $request->lastname;
        $candidates->position_id = $request->position_id;
        if(is_null($request->image)){
            $candidates->img_url = $image;
        }
        else {
            if(File::exists($image_path)){
                File::delete($image_path);
            }
            $candidates->img_url = "/images/" . $filename;
        }
        
        $candidates->event_id = $request->event_id;

        $candidates->save();

        return redirect()->route('events.show', $request->event_id)->with('message', 'Candidate updated successfully');

    }

    public function destroy($id)
    {
        
        $candidate = Candidate::find($id);
        $event_id = $candidate->event_id;
        $candidate->delete();
        return redirect()->route('events.show', $event_id)->with('message', 'Candidate DELETED');

    }
}

resources/views/candidates/candidates.blade.php
@extends('layouts.layouts')

@section('title', 'Create Candidate')

@section('content')
	<div class="container">
	<h3> Candidate Details </h3>
	{!! Form::open(['route' => 'candidates.store', 'Method' => 'POST']) !!}

		{!! Form::label('Lastname') !!}
		{!! Form::text('lastname', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '20']) !!}

		{!! Form::label('Firstname') !!}
		{!! Form::text('firstname', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '20']) !!}

		{!! Form::label('Position') !!}
		{!!  Form::select('select', ['1' => 'President', '2' => 'Vice President', '3' => 'Secretary', '4' => 'treasurer'],  'S', ['class' => 'form-control' ]) !!}

		{!! Form::submit('Save', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}

	{!! Form::close() !!}
	</div>
	@if(count( $errors ) > 0)
		<ul class="alert alert-danger">
			@foreach($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	@endif
@endsection

@section('scripts')
	<script type = "text/javascript">
	</script>
@endsection

resources/views/candidates/edit.blade.php
@extends('layouts.layouts')

@section('title', 'Update Candidate')

@section('content')
	<div class="container">
	<h3> Update Candidate </h3>
	{!! Form::model($candidates, ['route' => ['candidates.update', $candidates->id]]) !!}

		{!! Form::label('Lastname') !!}
		{!! Form::text('lastname', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '20']) !!}

		{!! Form::label('Firstname') !!}
		{!! Form::text('firstname', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '20']) !!}

		{!! Form::label('Alias') !!}
		{!! Form::text('alias', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '20']) !!}

		{!! Form::label('Position') !!}
		{!! Form::text('position', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '20']) !!}

		{!! Form::label('Platform') !!}
		{!! Form::text('platform', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '20']) !!}

  		{{ method_field('PUT') }}﻿
  		
		{!! Form::submit('UPDATE', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}

	{!! Form::close() !!}
	</div>
	@if(count( $errors ) > 0)
		<ul class="alert alert-danger">
			@foreach($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	@endif
@endsection

@section('scripts')
	<script type = "text/javascript">
	</script>
@endsection

resources/views/candidates/index.blade.php
@extends('layouts.layouts')

@section('title', 'Student List')

@section('content')

	<div class = "container">
		<h3> List of Candidates </h3>
		@if(Session::has('message'))
			<div class="alert alert-success">
				{{ Session::get('message') }}
			</div>
		@endif

		<a class="btn btn-primary" href="{{ route('candidates.create') }}" role="button">Add Candidate</a>

		<table class = 'table table-hover'>
			<thead>
				<tr>
					<th>Lastname</th>
					<th>Firstname</th>
					<th>Position</th>
					<th>Action</th>
				</tr>
			</thead>

			<tbody>
				@foreach($candidate as $candidate)
					<tr>
						<td> {{ $candidate->lastname }}</td>
						<td> {{ $candidate->firstname }}</td>
						<td> {{ $candidate->position }}</td>
						<td> 
							<a href="{{ 'candidates/'. $candidate->id .'/edit' }}" type="button" class="btn btn-success" aria-label="Left Align">
  								<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
							</a>
						</td>
					</tr>
				@endforeach
			</tbody>
		</table>
		{{-- {{ $candidate->links() }} --}}
	</div>

@endsection