routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::user()){
    	return redirect()->route('events.index');
	}
	else{
		return redirect()->route('login');
	}
});
/*Route::get('/', function(\Illuminate\http\Request $request){
	$user = $request->user();
	//dd($user->hasRole('Admin'));
	//Change to when having can
	dd($user->can('Add Candidate'));
});*/

// Authenticated Web Pages
//Route::group(['middleware' => 'auth'], function(){
Route::resource('candidates', 'CandidateController');
Route::resource('students', 'StudentController');
Route::resource('positions', 'PositionController');
Route::resource('results', 'ResultController');
Route::resource('votes', 'VoteController');
Route::resource('events', 'EventController');
Route::resource('users', 'UserController');
Route::post('votes/{votes}/validate', 'VoteController@ValidateStudent')->name('votes.ValidateStudent');
Route::post('votes/{votes}/start', 'VoteController@StartVoting')->name('votes.StartVoting');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Event.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $table = 'events';

    protected $primaryKey = 'id';

    protected $fillable = ['description', 'start_date', 'end_date'];
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Event;
use App\Candidate;
use App\Student;
use App\Position;
use Carbon\Carbon; 
use Auth;
use Session;

class EventController extends Controller
{
    public function index()
    {
        if(Auth::user()){
            $events = Event::simplePaginate(100);
            $today_date = Carbon::now();
            
            foreach ($events as $event) {
                $enddate = Carbon::createFromFormat('Y-m-d', $event-> end_date);
                $data_difference = $today_date->diffInDays($enddate, false);

                if($data_difference > 0) {
                    $data = Event::find($event -> id);
                    $data->status = 'Active';
                    $data->save();
                    // $event -> status = 'Active';
                }

                elseif($data_difference < 0) {
                    $data = Event::find($event -> id);
                    $data->status = 'Inactive';
                    $data->save();
                    // $event -> status = 'Inactive';
                }

                else {
                    $data = Event::find($event -> id);
                    $data->status = 'Active';
                    $data->save();
                    // $event -> status = 'Active';
                }
            }
            return view('events.list')->with('events', $events);
            

        }
        else{
            return redirect()->route('login');
        }
    }

    public function create()
    {
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'description'=>'required|min:1',
            'start_date'=>'required|after:yesterday',
            'end_date'=>'required|after:start_date',
            ]);

        $events = New Event;

        $events->description = $request -> description;
        $events->start_date = $request -> start_date;
        $events->end_date = $request -> end_date;
        $events->status = 'Active';

        $events->save();

        return redirect()->route('events.index')->with('message', 'Event added successfully');
    }

    public function show($id)
    {
        $events = Event::find($id);
        $candidates = Candidate::where('event_id', $id)->orderBy('position_id')->paginate(100);
        $students = Student::where('event_id', $id)->paginate(50, ['*'], 'studShow');
        $courses = Student::select('course')->distinct()->pluck('course', 'course')->toArray();
        $positions = Position::where('event_id', $id)->paginate(10, ['*'], 'candShow');
        $positions1 = Position::where('event_id', $id)->pluck('description', 'id');
        return view('events.eventdetails')->with('courses', $courses)->with('events', $events)->with('candidates', $candidates)->with('students', $students)->with('positions', $positions)->with('positions1', $positions1)->with(compact('studShow', 'candShow'));
    }   

    public function edit($id)
    {
    }

    public function update(Request $request, $id)
    {

        $events = Event::find($request->input('id'));

        $events->description = $request->description;
        $events->start_date = $request->start_date;
        $events->end_date = $request->end_date;

        $events->save();
        return redirect()->route('events.index')->with('message', 'Event updated successfully');
    }

    public function destroy($id)
    {
        dd($id);
        $students = Student::where('event_id', $id)->destroy();
        return redirect()->route('events.show', $event_id)->with('message', 'Cleared Students List');
    }
}

resources/views/events/create.blade.php
@extends('layouts.layouts')

@section('title', 'Create Event')

@section('content')
	<div class="container">
	<h3> Event </h3>
	{!! Form::open(['route' => 'events.store', 'Method' => 'POST']) !!}

		{!! Form::label('Event Description') !!}
		{!! Form::text('description', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '100']) !!}

		{!! Form::label('Start Date') !!}
		{!! Form::date('start_date', null, ['class' => 'form-control', 'required' => '']) !!}
		{!! Form::label('End Date') !!}
		{!! Form::date('end_date', null, ['class' => 'form-control', 'required' => '']) !!}

		{!! Form::submit('Save', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}

	{!! Form::close() !!}
	</div>
	@if(count( $errors ) > 0)
		<ul class="alert alert-danger">
			@foreach($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	@endif
@endsection
	
@section('scripts')
	<script type = "text/javascript">
	</script>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.layouts')

@section('title', 'Update Event')

@section('content')
	<div class="container">
	<h3> Update Event </h3>
	{!! Form::model($events, ['route' => ['events.update', $events->id]]) !!}

		{!! Form::label('Event Description') !!}
		{!! Form::text('description', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '100']) !!}

		{!! Form::label('Start Date') !!}
		{!! Form::date('start_date', null, ['class' => 'form-control', 'required' => '']) !!}
		
		{!! Form::label('End Date') !!}
		{!! Form::date('end_date', null, ['class' => 'form-control', 'required' => '']) !!}

		{{ method_field('PUT') }}﻿

		{!! Form::submit('Update', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}

	{!! Form::close() !!}
	</div>
	@if(count( $errors ) > 0)
		<ul class="alert alert-danger">
			@foreach($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	@endif
@endsection

@section('scripts')
	<script type = "text/javascript">
	</script>
@endsection

resources/views/events/list.blade.php
@extends('layouts.layouts')

@section('title', '| Events')

@section('nav_title', 'Event')

@section('content')

@if(Session::has('message'))
<div class="alert alert-success">
    {{ Session::get('message') }}
</div>
@endif

@if(count( $errors ) > 0)
    <ul class="alert alert-danger">
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

<h1 class="page-header">Events</h1>
<div class="row pull-left">
    @can('Add')
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addEvent">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Event
    </button>
    @endcan
</div>

<div id = "event_table">
    <table class = 'table table-hover'>
        <thead>
            <th> Description </th>
            <th> Start  </th>
            <th> End </th>
            <th> Status </th>
            <th> Action </th>
        </thead>
        <tbody>
        @foreach($events as $event)
            <tr>
                <td> {{ $event -> description}} </td>
                <td> {{ $event -> start_date}} </td>
    	        <td> {{ $event -> end_date }} </td>
                <td>  {{ $event -> status }}</td>
                <td>
                    <a href="{{ route('events.show', $event->id) }}" type="button" class="btn btn-success" aria-label="Left Align">
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                    </a>
                    @can('Edit')
                    <button class="edit-modal btn btn-success" data-toggle="modal" data-target="#editEvent" data-id="{{ $event->id }}" data-description="{{ $event->description }}" data-startdate="{{ $event->start_date }}" data-enddate="{{ $event->end_date }}">
                    <span class="glyphicon glyphicon-pencil"></span>
                    </button>
                    @endcan
                    <a href="{{ route('votes.show', $event->id) }}" type="button" class="btn btn-success" aria-label="Left Align">
                    <span class="glyphicon glyphicon-share" aria-hidden="true"></span>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    {{ $events->links() }}
</div>
@endsection

@section('modal')
<!-- Edit Event Modal -->
<div id="editEvent" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="panel panel-primary">
              <div class="panel-heading">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="panel-title" id="myModalLabel"><b>Edit Event</b></h4>
              </div>
            <div class="modal-body">
              @if(isset($event->id))
                {!! Form::model($event, ['route' => ['events.update', $event->id], 'method' => 'PUT']) !!}
                    {!! Form::hidden('id', null, ['id' => 'uid', 'class' => 'form-control', 'required' => '']) !!}

                    {!! Form::label('description', 'Description:') !!}
                    {!! Form::text('description', null, ['id' => 'eventdesc', 'class' => 'form-control', 'required' => '', 'maxlength' => '100']) !!}

                    {!! Form::label('start_date', 'Start Date:') !!}
                    {!! Form::date('start_date', null, ['id' => 'eventstart', 'class' => 'form-control', 'required' => '']) !!}

                    {!! Form::label('end_date', 'End Date:') !!}
                    {!! Form::date('end_date', null, ['id' => 'eventend', 'class' => 'form-control', 'required' => '']) !!}

                    <div class="modal-footer">
                      <button type="button" class="btn btn-primary" data-dismiss="modal" style="margin-top:20px">Cancel</button>
                      {!! Form::submit('Update', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}
                    </div>
                {!! Form::close() !!}
              @endif
            </div>
          </div>
        </div>
    </div>

<!-- Add Event Modal -->
    <div class="modal fade" id="addEvent" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="panel panel-primary">
          <div class="panel-heading">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="panel-title" id="myModalLabel"><b>Add Event</b></h4>
          </div>
          <div class="modal-body">
            {!! Form::open(['route' => 'events.store', 'Method' => 'POST']) !!}

            {!! Form::label('Event Description') !!}
            {!! Form::text('description', null, ['class' => 'form-control', 'required' => '', 'maxlength' => '100']) !!}

            {!! Form::label('Start Date') !!}
            {!! Form::date('start_date', null, ['class' => 'form-control', 'required' => '']) !!}

            {!! Form::label('End Date') !!}
            {!! Form::date('end_date', null, ['class' => 'form-control', 'required' => '']) !!}

            {!! Form::submit('Save', ['class' => 'btn btn-success', 'style' => 'margin-top: 20px']) !!}

            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
@endsection

@section('scripts')
@parent
{{-- Edit Event Modal --}}
<script type="text/javascript">
    $(document).on('click', '.edit-modal', function() {
        $('#uid').val($(this).data('id'));
        $('#eventdesc').val($(this).data('description'));
        $('#eventstart').val($(this).data('startdate'));
        $('#eventend').val($(this).data('enddate'));
        $('#editEvent').modal('show');
    });
</script>
@endsection