routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if(Auth::user()){
    	return redirect()->route('events.index');
	}
	else{
		return redirect()->route('login');
	}
});
/*Route::get('/', function(\Illuminate\http\Request $request){
	$user = $request->user();
	//dd($user->hasRole('Admin'));
	//Change to when having can
	dd($user->can('Add Candidate'));
});*/

// Authenticated Web Pages
//Route::group(['middleware' => 'auth'], function(){
Route::resource('candidates', 'CandidateController');
Route::resource('students', 'StudentController');
Route::resource('positions', 'PositionController');
Route::resource('results', 'ResultController');
Route::resource('votes', 'VoteController');
Route::resource('events', 'EventController');
Route::resource('users', 'UserController');
Route::post('votes/{votes}/validate', 'VoteController@ValidateStudent')->name('votes.ValidateStudent');
Route::post('votes/{votes}/start', 'VoteController@StartVoting')->name('votes.StartVoting');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>SPC Elections</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        San Pedro College Elections
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/layouts.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="icon" href="https://getbootstrap.com/docs/3.3/favicon.ico">

	<title>
		San Pedro College Commission on Elections | @yield('title')
	</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="{{ asset('css/dashboard.css') }}" rel="stylesheet">

</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="https://getbootstrap.com/docs/3.3/examples/dashboard/#">
          	San Pedro College Commission on Elections | @yield('nav_title')
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{{ route('logout') }}"
            onclick="event.preventDefault();
                  document.getElementById('logout-form').submit();">
            Logout
              </a>
            </li>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <img src = "{{ url('/images/logos/spc.png') }}" class="image-responsive nav-img">
          <img src = "{{ url('/images/logos/comelec.png') }}" class="image-responsive nav-img">
          <ul class="nav nav-sidebar">
            @if(Auth::user())
              <h4><center> Welcome, </center></h4>
             <center><h3>{{ Auth::user()->name }}</h3></center>
            @endif
            <li><a href = "{{ route('events.index') }}"> Events </a></li>
            @can('View')
              <li><a href = "{{ route('users.index') }}"> Users </a></li>
            @endcan
          	@yield('sidebar')
            <li>
              <a target = "_blank" href = "https://docs.google.com/document/d/1_M9ZRH0QB4XsujIhUEZtb08pFNVya_AzNyCQl8Dx_1c/edit?usp=sharing"><h6>Developer Notes</h6></a>
            </li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        	@yield('content')
        </div>
      </div>
    </div>

    <nav class="navbar navbar-inverse navbar-fixed-bottom">
      <div class="container-fluid">
        <div class="navbar-header">
             <h6>Lead Developer: Ferdinand A. Polpol | Co-Developer: John Carlos L. Ochave</h6>
        </div>
      </div>
    </nav>

@yield('modal')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
@yield('scripts') 
</body>
</html>

<style>
html, body{
  font-family: "Century Gothic", CenturyGothic, AppleGothic, sans-serif;
}
.navbar{
  background-color:	#21255e;
  color: #fff;
}
.navbar-fixed-bottom{
   background-color:	#21255e;
}

.nav-img{
  width: 100px;
  height: 130px;
  margin-left: 25px;
  margin-right: auto;
}
</style>

resources/views/layouts/layouts_v.blade.php
<!DOCTYPE html>
<html lang="en">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>Voting | @yield('title') </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{{ asset('css/cover.css') }}" rel="stylesheet">

</head>

<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <div class="masthead clearfix">
          <div class="inner">
            <h3 class="masthead-brand">@yield('brand')</h3>
          </div>
        </div>

        <div class="inner cover">
          <h1 class="cover-heading">@yield('cover')</h1>
          @yield('content')
        </div>

        <div class="mastfoot">
            <p>Lead Developer: Ferdinand A. Polpol | Co-Developer: John Carlos L. Ochave</p>
        </div>
      </div>
    </div>
  </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"><script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
@yield('script')
</body></html>

<style>
html, body{
  background-color: #21255e;
  font-family: "Century Gothic", CenturyGothic, AppleGothic, sans-serif;
	background-image: url('/images/bg/spc.jpg');
	background-repeat: no-repeat;
	background-size: 100% 100%;
}
</style>